# Generated by Django 2.1 on 2018-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
