# Generated by Django 2.1 on 2018-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180802_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='es_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='es_feedback',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Enter the question text that you want displayed', verbose_name='Question'),
        ),
    ]
