# Generated by Django 2.1 on 2018-08-04 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180803_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
