# Generated by Django 2.1 on 2018-08-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180805_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.TextField()),
                ('false', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_scoreable',
        ),
        migrations.AddField(
            model_name='right',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AddField(
            model_name='right',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quiz'),
        ),
    ]
