# Generated by Django 2.1 on 2018-08-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180805_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='question',
        ),
    ]
