# Generated by Django 2.1 on 2018-08-05 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='quizes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
