# Generated by Django 2.1 on 2018-08-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180806_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Quiz'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='right',
            name='false',
        ),
        migrations.AddField(
            model_name='right',
            name='false',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='right',
            name='right',
        ),
        migrations.AddField(
            model_name='right',
            name='right',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
