# Generated by Django 2.1 on 2018-08-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180806_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='date',
        ),
    ]
