# Generated by Django 2.1 on 2018-08-07 06:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
        migrations.AddField(
            model_name='response',
            name='false',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='right',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2018, 8, 7)),
        ),
        migrations.AlterField(
            model_name='response',
            name='quiz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Quiz'),
        ),
        migrations.AlterField(
            model_name='response',
            name='quizes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
