# Generated by Django 2.1 on 2018-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_response_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='q',
            field=models.TextField(blank=True),
        ),
    ]
