# Generated by Django 2.1 on 2018-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180807_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='false',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='right',
            field=models.TextField(blank=True),
        ),
    ]
