# Generated by Django 2.1 on 2018-08-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180807_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.TextField(blank=True)),
                ('false', models.TextField(blank=True)),
                ('question', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='false',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='right',
        ),
    ]
