# Generated by Django 2.1 on 2018-08-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180807_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Response'),
            preserve_default=False,
        ),
    ]
